[project]
name = "minimal-browser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.8.0",
    "pyqt6-webengine>=6.8.0",
    "rich>=13.9.4",
    "textual>=1.0.0",
]

[tool.uv.workspace]
members = ["pyside"]
